// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtJbTln05-kDuCcwXdoABu9wnauQ2zh3g',
    appId: '1:243937477237:web:135b9a4f5bc6063c116e3c',
    messagingSenderId: '243937477237',
    projectId: 'appgk-fceff',
    authDomain: 'appgk-fceff.firebaseapp.com',
    storageBucket: 'appgk-fceff.appspot.com',
    measurementId: 'G-77WY84Y1YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvkF8iGY6c5m0d11MUA6ilKQYqNd7D28',
    appId: '1:243937477237:android:2fcebf26846d964c116e3c',
    messagingSenderId: '243937477237',
    projectId: 'appgk-fceff',
    storageBucket: 'appgk-fceff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvvQaJ6SesIaFMRBLqSm1KBSGRBKJD8Z0',
    appId: '1:243937477237:ios:f5efec942857459c116e3c',
    messagingSenderId: '243937477237',
    projectId: 'appgk-fceff',
    storageBucket: 'appgk-fceff.appspot.com',
    iosBundleId: 'com.example.appGk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvvQaJ6SesIaFMRBLqSm1KBSGRBKJD8Z0',
    appId: '1:243937477237:ios:f5efec942857459c116e3c',
    messagingSenderId: '243937477237',
    projectId: 'appgk-fceff',
    storageBucket: 'appgk-fceff.appspot.com',
    iosBundleId: 'com.example.appGk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtJbTln05-kDuCcwXdoABu9wnauQ2zh3g',
    appId: '1:243937477237:web:900eb427f4b7de1c116e3c',
    messagingSenderId: '243937477237',
    projectId: 'appgk-fceff',
    authDomain: 'appgk-fceff.firebaseapp.com',
    storageBucket: 'appgk-fceff.appspot.com',
    measurementId: 'G-58EP8HG2CT',
  );
}
